name: Generate and Deploy index.html

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Run HTML generator
      run: |
        echo "Generating index.html from README.md"
        node generate-html.js
        echo "=== Output files ==="
        ls -alh
        cat index.html

    - name: Deploy index.html manually to gh-pages
      run: |
        mkdir gh-pages
        cp index.html gh-pages/
        cd gh-pages
        git init
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Deploy index.html"
        git branch -M gh-pages
        git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages