name: Generate Comparison HTML

# 觸發條件：每次 commit
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-html:
    runs-on: ubuntu-latest

    steps:
      # 1. 簽出程式碼
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 設定 Python 環境
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. 安裝依賴（如果需要）
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      # 4. 解析 README.md 並生成 index.html
      - name: Generate comparison HTML
        run: |
          python -c "
import re

# 讀取 README.md
with open('README.md', 'r', encoding='utf-8') as f:
    content = f.read()

# 解析 en 和 zh-tw 內容
en_match = re.search(r'\"\"\"en\n(.*?)\"\"\"end', content, re.DOTALL)
zh_tw_match = re.search(r'\"\"\"zh-tw\n(.*?)\"\"\"', content, re.DOTALL)

en_text = en_match.group(1).strip() if en_match else 'No English content found'
zh_tw_text = zh_tw_match.group(1).strip() if zh_tw_match else 'No Chinese content found'

# 按段落分割（兩次換行）
en_paragraphs = [p.strip() for p in en_text.split('\n\n') if p.strip()]
zh_tw_paragraphs = [p.strip() for p in zh_tw_text.split('\n\n') if p.strip()]

# 生成 HTML
html = '''
<!DOCTYPE html>
<html lang=\"en\">
<head>
    <meta charset=\"UTF-8\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
    <title>README Comparison</title>
    <style>
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th, td { border: 1px solid #ddd; padding: 12px; text-align: left; vertical-align: top; }
        th { background-color: #f2f2f2; font-weight: bold; }
        td { line-height: 1.5; }
        h1 { font-family: Arial, sans-serif; }
    </style>
</head>
<body>
    <h1>README Content Comparison</h1>
    <table>
        <tr>
            <th>English</th>
            <th>繁體中文</th>
        </tr>
'''

# 按段落比較，補齊空段落
max_paragraphs = max(len(en_paragraphs), len(zh_tw_paragraphs))
for i in range(max_paragraphs):
    en_para = en_paragraphs[i] if i < len(en_paragraphs) else ''
    zh_tw_para = zh_tw_paragraphs[i] if i < len(zh_tw_paragraphs) else ''
    # 替換換行符為 <br> 以保留段落內換行
    en_para = en_para.replace('\n', '<br>')
    zh_tw_para = zh_tw_para.replace('\n', '<br>')
    html += f'<tr><td>{en_para}</td><td>{zh_tw_para}</td></tr>\n'

html += '''
    </table>
</body>
</html>
'''

# 寫入 index.html
with open('index.html', 'w', encoding='utf-8') as f:
    f.write(html)
          "

      # 5. 提交生成的 index.html 到儲存庫
      - name: Commit and push index.html
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add index.html
          git commit -m 'Update index.html with README paragraph comparison'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}